# ==================== Direct Deployment Script (PowerShell) ====================
# This script deploys the application using the direct workflow.
# This is a single-step deployment that builds and starts containers.
#
# Usage:
#   .\scripts\deploy-direct.ps1
#
# This is equivalent to:
#   aspire deploy -o .\
# ================================================================================

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

Write-Host "🚀 Direct deployment (integrated build + deploy)..." -ForegroundColor Cyan
Write-Host "   Project: $ProjectRoot\Aspire\AppHost" -ForegroundColor Gray
Write-Host ""

# Navigate to project root
Push-Location $ProjectRoot

try {
    # Deploy directly
    aspire deploy -o .\

    if ($LASTEXITCODE -eq 0) {
        # Detect project name generated by Aspire CLI (contains a hash, e.g. aspire-aspire-ecommerce-b3ce5819)
        $labels = docker ps --filter "label=com.docker.compose.service=catalog-api" `
            --format "{{.Labels}}" 2>$null | Select-Object -First 1
        $ProjectName = if ($labels -match 'com\.docker\.compose\.project=([^,]+)') { $Matches[1] } else { $null }

        if ($ProjectName) {
            # Save for later use by stop.ps1
            $ProjectName | Set-Content "$ProjectRoot\Aspire\.aspire-project"
            Write-Host "   Project name: $ProjectName" -ForegroundColor DarkGray
        } else {
            Write-Warning "Could not detect Aspire project name. Use scripts\stop.ps1 to stop containers."
        }

        Write-Host ""
        Write-Host "✅ Deployment successful!" -ForegroundColor Green
        Write-Host ""
        Write-Host "📊 Container status:" -ForegroundColor Cyan
        if ($ProjectName) {
            docker compose -p $ProjectName -f "Aspire\docker-compose.yaml" ps
        } else {
            docker ps
        }
        Write-Host ""
        Write-Host "📝 Useful commands:" -ForegroundColor Yellow
        Write-Host "   View logs: .\scripts\stop.ps1 -Logs" -ForegroundColor Gray
        Write-Host "   Stop:      .\scripts\stop.ps1" -ForegroundColor Gray
        Write-Host "   Restart:   .\scripts\stop.ps1 -Restart" -ForegroundColor Gray
    } else {
        Write-Host ""
        Write-Host "❌ Deployment failed" -ForegroundColor Red
        exit 1
    }
} finally {
    Pop-Location
}
