#!/bin/bash
# ==================== Direct Deployment Script ====================
# This script deploys the application using the direct workflow.
# This is a single-step deployment that builds and starts containers.
#
# Usage:
#   ./scripts/deploy-direct.sh
#
# This is equivalent to:
#   aspire deploy -o .\
# ===================================================================

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "🚀 Direct deployment (integrated build + deploy)..."
echo "   Project: $PROJECT_ROOT/Aspire/AppHost"
echo ""

# Navigate to project root
cd "$PROJECT_ROOT"

# Deploy directly
aspire deploy -o ./

if [ $? -eq 0 ]; then
    # Detect project name generated by Aspire CLI (contains a hash, e.g. aspire-aspire-ecommerce-b3ce5819)
    PROJECT_NAME=$(docker ps --filter "label=com.docker.compose.service=catalog-api" \
        --format "{{.Labels}}" 2>/dev/null | head -1 | \
        sed -n 's/.*com\.docker\.compose\.project=\([^,]*\).*/\1/p')

    if [ -n "$PROJECT_NAME" ]; then
        # Save for later use by stop.sh
        echo "$PROJECT_NAME" > "$PROJECT_ROOT/Aspire/.aspire-project"
        echo "   Project name: $PROJECT_NAME"
    else
        echo "⚠️  Could not detect Aspire project name. Use ./scripts/stop.sh to stop containers."
    fi

    echo ""
    echo "✅ Deployment successful!"
    echo ""
    echo "📊 Container status:"
    if [ -n "$PROJECT_NAME" ]; then
        docker compose -p "$PROJECT_NAME" -f "Aspire/docker-compose.yaml" ps
    else
        docker ps
    fi
    echo ""
    echo "📝 Useful commands:"
    echo "   View logs: ./scripts/stop.sh --logs"
    echo "   Stop:      ./scripts/stop.sh"
    echo "   Restart:   ./scripts/stop.sh --restart"
else
    echo ""
    echo "❌ Deployment failed"
    exit 1
fi
